### ISSUE TITLE
[Chore]: Add more local development instructions

### ISSUE THREAD

**Issue by jordanharris-6** [bigbite/build-tools#114]
### The feature

When I was developing locally. I didn't know how to update my project with the latest version of build tools using yalc. I later learned that once you have made changes to build tools and ran `yalc publish` you then need to run `yalc push` and in the project you want to use it in you need to run `yalc update` so it uses the new version. I think adding these steps to the readme would be good for other users developing locally.

**Comment by ampersarnie** [comment]
Closed with merge of #115
