### ISSUE TITLE
[Bug]: Builds not working on CircleCI

### ISSUE THREAD

**Issue by g-elwell** [bigbite/build-tools#28]
### What happened?

I have the following commands added to my package.json:
```
"scripts": {
    "watch:dev": "build-tools build",
    "build:prod": "build-tools build --once --production"
  },
```
Both work as expected locally, but the CLI seems to be having issues locating projects in a CI environment.

- In a project that uses the build tools within `wp-content` in *site-wide* mode, once pushed to CI, the build-tools will default to *single-project* mode - [log](https://app.circleci.com/pipelines/github/bigbite/bigbite-v3/106/workflows/f2b4409f-b600-45c4-9bcc-1c7952a7e34b/jobs/100/parallel-runs/0/steps/0-113)
- Adding the `--site` flag doesn't seem to have any impact on this behaviour - [log](https://app.circleci.com/pipelines/github/bigbite/bigbite-v3/108/workflows/ad2a803f-fd96-4b94-9c25-55330561aad0/jobs/101/parallel-runs/0/steps/0-113)
- However passing a specific project positional will work - [log](https://app.circleci.com/pipelines/github/bigbite/bigbite-v3/110/workflows/489967e4-2aaf-4663-a978-62e3d341e3d1/jobs/102/parallel-runs/0/steps/0-113)

Note that `bbv3` is the project name in the root `package.json`, which is what is being picked up in the first 2 instances, `bigbitev3` is the project name of the theme I'm trying to build.

On another project (a plugin), I'm using the build tools in *single-project* mode with the same commands as above. Again, all works fine locally but once pushed to CI the build will fail - [log](https://app.circleci.com/pipelines/github/bigbite/block-negative-margin/2/workflows/84a82d55-57a7-40fd-970c-5f65af7abd70/jobs/2/parallel-runs/0/steps/0-113)

### Which environments are you experiencing the issue on?

CI (CircleCI, Travis, etc)

### Relevant log output

```
> bbv3@1.0.0-alpha.1 build:prod
> build-tools build --once --production

Compiling single project in production mode.
Processing the following projects:
 * bbv3 build-tools build [projects] [production] [once] [site] [quiet]

Run a new build process.

Positionals:
  projects  Comma separated list of projects to compile.  [string] [default: ""]

Options:
      --production  Build and compile production assets.
                                                      [boolean] [default: false]
      --once        Only run the process once.        [boolean] [default: false]
      --site        Run the process from the root of a site, such as from
                    wp-content.                       [boolean] [default: false]
      --quiet       Limit the amount of noise by removing webpack output.
                                                      [boolean] [default: false]
  -h, --help        Show help                                          [boolean]
  -v, --version     Show version number                                [boolean]

TypeError: Cannot read properties of null (reading '0')
    at /home/circleci/project/node_modules/@bigbite/build-tools/src/commands/build.js:102:80
    at Array.forEach (<anonymous>)
    at Object.exports.handler (/home/circleci/project/node_modules/@bigbite/build-tools/src/commands/build.js:99:12)
    at /home/circleci/project/node_modules/yargs/build/index.cjs:1:9054
    at j (/home/circleci/project/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/home/circleci/project/node_modules/yargs/build/index.cjs:1:9023)
    at M.runCommand (/home/circleci/project/node_modules/yargs/build/index.cjs:1:7206)
    at Jt.[runYargsParserAndExecuteCommands] (/home/circleci/project/node_modules/yargs/build/index.cjs:1:56715)
    at Jt.parse (/home/circleci/project/node_modules/yargs/build/index.cjs:1:38938)
    at Object.<anonymous> (/home/circleci/project/node_modules/@bigbite/build-tools/src/cli.js:12:7)


Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by ampersarnie** [comment]
@g-elwell Thanks for the detailed bug report. I'd been concerned about this and are working on it in #18. Can you try using the `hotfix/ci-check` branch and see if you have any further luck with it (_I've not had chance to test it myself yet_).

**Comment by ampersarnie** [comment]
@g-elwell I've checked out your repo and branch with the build-tools update. Managed to debug this on CI and have pushed an additional change to the previously mentioned branch. I'm hoping this works without any further issue but I've not have chance to test as thoroughly as I'd like.

I'll be tidying up that PR as there's logic around this that - even though it works now - I've over complicated. I'll let you know as soon as I'm done.

**Comment by g-elwell** [comment]
@ampersarnie thanks for looking into this and also for checking out my repo.

It looks like there are actually two related issues in play:

1. Unable to detect full-site mode on CI
2. Single-project builds failing on CI

Your fix seems to have solved the first problem, which means the repo you inspected is now building correctly as it's now running in full-site mode.

In [another project](https://github.com/bigbite/block-negative-margin/tree/chore/update-ci) that _should_ run in single-project mode, the build is still failing:

```
> block-negative-margin@1.0.0-alpha build:prod
> build-tools build --site --once --production

Compiling single project in production mode.
Processing the following projects:
 * block-negative-margin build-tools build [projects] [production] [once] [site] [quiet]

Run a new build process.

Positionals:
  projects  Comma separated list of projects to compile.  [string] [default: ""]

Options:
      --production  Build and compile production assets.
                                                      [boolean] [default: false]
      --once        Only run the process once.        [boolean] [default: false]
      --site        Run the process from the root of a site, such as from
                    wp-content.                       [boolean] [default: false]
      --quiet       Limit the amount of noise by removing webpack output.
                                                      [boolean] [default: false]
  -h, --help        Show help                                          [boolean]
  -v, --version     Show version number                                [boolean]

TypeError: Cannot read properties of null (reading '0')
    at /home/circleci/project/node_modules/@bigbite/build-tools/src/commands/build.js:106:80
    at Array.forEach (<anonymous>)
    at Object.exports.handler (/home/circleci/project/node_modules/@bigbite/build-tools/src/commands/build.js:103:12)
    at /home/circleci/project/node_modules/yargs/build/index.cjs:1:9054
    at j (/home/circleci/project/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/home/circleci/project/node_modules/yargs/build/index.cjs:1:9023)
    at M.runCommand (/home/circleci/project/node_modules/yargs/build/index.cjs:1:7206)
    at Jt.[runYargsParserAndExecuteCommands] (/home/circleci/project/node_modules/yargs/build/index.cjs:1:56715)
    at Jt.parse (/home/circleci/project/node_modules/yargs/build/index.cjs:1:38938)
    at Object.<anonymous> (/home/circleci/project/node_modules/@bigbite/build-tools/src/cli.js:12:7)


Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by ampersarnie** [comment]
@g-elwell I've had a dig into the second problem and created a fix for it on the same branch (see commit [`250e0b1`](https://github.com/bigbite/build-tools/pull/18/commits/250e0b115800abbd4b7127cb0bc74f71a462aacb)) if you want to check it out. Again, that branch still needs some tidying up but it should allow you to continue.

**Comment by g-elwell** [comment]
@ampersarnie unfortunately that fix doesn't seem to have solved the issue for me, I'm still getting the same error in CI when attempting to build [this branch](https://github.com/bigbite/block-negative-margin/tree/chore/update-ci). Unless there's something I'm doing wrong?

**Comment by ampersarnie** [comment]
@g-elwell You need to rebuild you `package-lock.json` file as when you use a branch as a target it pins it at a specific commit rather than the branch itself, so rebuild will pull in new commits. I've rebuilt that for you (and removed the `--site` flag as you don't need it for a single project) and it's passing now.

**Comment by g-elwell** [comment]
Fantastic, thanks. I thought I did that tbf but clearly missed something.

**Comment by ampersarnie** [comment]
@g-elwell Closing this issue for now as we've got that fix in the works that covers this. But feel free to re-open or comment further if anything else around this issue comes up.
