### ISSUE TITLE
[Feature]: Linting Rules (JS) - Cyclomatic Complexity

### ISSUE THREAD

**Issue by jonmcp** [bigbite/build-tools#30]
### The feature

Our [PHPCS Config](https://github.com/bigbite/phpcs-config) enforces a maximum [Cyclomatic Complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of `10` for all PHP code. This forces users to refactor overly-complicated methods into more readable, maintainable structures.

The initial work to refactor code such that it satisfies this rule can be, admittedly, rather burdensome; so, realistically, it might not be wise to add the [ESLint rule](https://eslint.org/docs/rules/complexity) rule into existing projects.
However, the the long-term benefits can be quite significant in some cases, so I think it might be worth considering adding this rule for new projects.
Because of the old/new dichotomy, I wouldn't ordinarily suggest that it be added as part of the core Build Tools package, but the chances of folks remembering to add it in manually to new projects would be quite low. I think that allowing folks to instead turn the rule off on a per-project basis is probably the better approach.

**Comment by ampersarnie** [comment]
@jonmcp Thanks. I agree that there's a lot of potential here to create a rather burdensome addition here. Because we need a large amount of lead time for something like this I'm pencilling it in for `1.3` this can definitely be brought forward but that will give enough time for internal teams to become aware and allow reasonable time for adjustments.

**Comment by ampersarnie** [comment]
Moved this to be released in `1.0` I'd much rather have this implemented now before we have wider adoption as later will have the potential to increase that burden for other engineers and having to refactor or change some of their work.
