### ISSUE TITLE
[Bug]: pnpm install fails due to fibers package (obsolete)

### ISSUE THREAD

**Issue by markgoodyear** [bigbite/build-tools#73]
### What happened?

Testing `pnpm`, it fails on the install due to this package: https://www.npmjs.com/package/fibers. 

States in the docs it is obsolete and doesn't support Node 16+. I can't see where it is used within the build tools so looks safe to remove this package, whether we use pnpm or not.

### Expected
No issues when installing dependencies.

### Which environments are you experiencing the issue on?

CLI (macOS, Windows, etc)

### Relevant log output
```
node_modules/.pnpm/fibers@5.0.3/node_modules/fibers: Running install script...
 ELIFECYCLE  Command failed.
```

**Comment by ampersarnie** [comment]
`fibers` package has been removed in [release `1.1.2`](https://github.com/bigbite/build-tools/releases/tag/1.1.2).
