### ISSUE TITLE
Importing @wordpress packages from node_modules?

### ISSUE THREAD

**Issue by ampersarnie** [bigbite/build-tools#9]
### Discussed in https://github.com/bigbite/build-tools/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **g-elwell** November 11, 2021</sup>
If you're working on a project and want to use the JavaScript APIs and libraries provided by WordPress, there are two options available:
- Destructure from the wp global variable (e.g. `const { ToggleControl } = wp.components`)
- Install from npm and import from node_modules (e.g. `import { ToggleControl } from '@wordpress/components`)

I was curious about the difference between these and wanted to know which one is the recommended approach. I couldn't find a clear answer, but while looking into it I discovered some interesting info that might be relevant to these build tools.

Destructuring is quick - you don't need to manually install a package and when developing for WordPress you can be certain that the global wp variable is going to be available when your code will run. However, because your code editor isn't aware of the wp global it can't provide you with any hinting or suggestions when you use it.

If you decide to install the packages you need using npm, your code editor can read their contents in order to provide some helpful tooling. In VSCode without any additional config you get suggestions, autocomplete and inline documentation about available imports, function params and component props as well as automatic import suggestions.

As a side note you end up recording which version of each package you are using in your project which might also be useful.

The downside to this approach is that you're importing packages that are already available to you in WordPress and increasing your bundle size needlessly. However, by listing these packages as externals in webpack you can prevent them from being added to your final bundle whilst still benefitting from the improved dev experience.

WordPress actually provide [@wordpress/dependency-extraction-webpack-plugin](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-dependency-extraction-webpack-plugin/) which defines all the modern WordPress packages and libraries as externals in webpack. Also, this plugin will generate a php file for each of your entrypoints containing a dependency array that you can import when you enqueue your script, removing the need to manually maintain an array of dependencies for each of your scripts.

In terms of these build tools, on a basic level adding the `@wordpress/*` packages to the webpack config as externals should be fairly straightforward and would allow you to choose which approach you want to take when it comes to using them in your project.</div>

**Comment by g-elwell** [comment]
Fixed in https://github.com/bigbite/build-tools/pull/58
